---
title: "Untitled"
author: "Katie"
date: '2022-10-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r}
# Not sure if necessary... was an issue with a version conflict... try new version in the future again...
#devtools::install_version("RPostgres", version = "1.2.1", repos = "http://cran.us.r-project.org")

### general options
Sys.setenv(LANG = "en")
options("scipen" = 100, "digits" = 4) # override R's tendency to use scientific notation

### Clean workspace
rm(list=ls())
graphics.off()

### Load packages (maybe need to be installed first)
# Standard
library(tidyverse) # General DS toolkit
library(magrittr) # For advanced piping

library(EconGeo)

# Databases
library(DBI) # GEneral R database interface
library(RPostgres) # PostgreSQL interface driver 
library(dbplyr) # for dplyr with databases

# Dataviz
library(kableExtra)
library(treemapify)
```


# Data

## Connect to database

```{r}
# Load script with variables
source("../variables.R")

# set up connection to existing PostgreSQL database, just plug in own details
con <- dbConnect(drv = RPostgres::Postgres(), 
                 dbname = var_dbname,
                 host = var_host, 
                 port = var_port,
                 user = var_user, 
                 password = var_password,
                 sslmode = 'require'
                 )

rm(var_dbname, var_host, var_password, var_port, var_user)
```

```{r}
con %>% dbListTables() %>% sort()
```
# TODOs

* Note: Maybe only IP5 patents? or contrast domestic with IP5?
* Country patent quality
* Consider different sim threshholds? Distribution 
* Compare with top r&d performer statistics


```{r}
# General
tbl_appln <- tbl(con, 'tls201_appln')
tbl_pers_appln <- tbl(con, 'tls207_pers_appln') 
tbl_person <- tbl(con, 'tls206_person')
tbl_appln_docb <- tbl(con, 'tls228_docdb_fam_citn')

tbl_appln_tech_field <- tbl(con, 'tls230_appln_techn_field')
tbl_appln_title <- tbl(con, 'tls202_appln_title')
tbl_appln_techn_field <- tbl(con, 'tls230_appln_techn_field')
tbl_appln_nace2 <- tbl(con, 'tls229_appln_nace2')

#OECD
tbl_appln_quality <- tbl(con, 'xtra_oecd_quality')

# Neuroscience
tbl_neuro_appln <- tbl(con, 'xtra_neuro_appln') #Ex. Cluster = technologies related to neuro; Cos_dist = how close to particular cluster (lower value = higher relatedness), # Cluster_main is the newly defined cluster (some patents are in multiple clusters, so we only filter 1 cluster that is most related to that application)
tbl_neuro_person_appln <- tbl(con, 'xtra_neuro_person_appln')
tbl_neuro_person <- tbl(con, 'xtra_neuro_person')
tbl_neuro_appln_ipc <- tbl(con, 'xtra_neuro_appln_ipc')
#tbl_neuro_priority <- tbl(con, 'xtra_priority_subsequent') #new as of 17th Feb
tbl_neuro_geo_appln_applicant <- tbl(con, 'xtra_neuro_geo_appln_applicant') #of firms (applicants)
tbl_neuro_geo_appln_inventor <- tbl(con, 'xtra_neuro_geo_appln_inventor') #of person (inventor)

```


```{r}
# define table query
tbl_citing_psn <- tbl_neuro_appln %>%
  # select docdb
  select(docdb_family_id) %>%
  distinct(docdb_family_id) %>%
  # join with family citations
  inner_join(tbl_appln_docb, by = "docdb_family_id") %>%
  # get citation age from application table
  left_join(tbl_appln %>% select(docdb_family_id, appln_filing_year), by = c("cited_docdb_family_id" = "docdb_family_id") )
```

```{r}
# collect
citing_psn <- tbl_citing_psn %>%
  collect()
```

```{r}
# getting only the earliest citing application on level of the citing docdbfamily
citing_psn %>%
  group_by(docdb_family_id, cited_docdb_family_id) %>%
  slice_min(appln_filing_year, n = 1, with_ties = FALSE) %>%
  ungroup()
```

